networks:
  cicd_network:
    external: true

services:
  jenkins:
    image: aazhernakov/jenkins-with-mvn
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cicd_network
    privileged: true
    environment:
      DOCKER_HOST: "tcp://host.docker.internal:2375"
    depends_on:
      - nexus

  nexus:
    image: sonatype/nexus3
    restart: always
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - cicd_network

volumes:
  jenkins_home:
  nexus-data:
